// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUCz5pX9zyKd3-dWdJ6SxowYAN1HaFmuE',
    appId: '1:287810725765:web:9f2ed040108ec4a4d446ec',
    messagingSenderId: '287810725765',
    projectId: 'otomobil2',
    authDomain: 'otomobil2.firebaseapp.com',
    storageBucket: 'otomobil2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMJ0fIWAoVhH9zw3ZIFRcU8KX9zN-Rh4',
    appId: '1:287810725765:android:65705427a877511fd446ec',
    messagingSenderId: '287810725765',
    projectId: 'otomobil2',
    storageBucket: 'otomobil2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfCzLF45-P41BCYrD9VsC__0AxSkO0ezw',
    appId: '1:287810725765:ios:c7e84844fb5ababdd446ec',
    messagingSenderId: '287810725765',
    projectId: 'otomobil2',
    storageBucket: 'otomobil2.appspot.com',
    iosBundleId: 'com.example.otomobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfCzLF45-P41BCYrD9VsC__0AxSkO0ezw',
    appId: '1:287810725765:ios:a782be632dbe359fd446ec',
    messagingSenderId: '287810725765',
    projectId: 'otomobil2',
    storageBucket: 'otomobil2.appspot.com',
    iosBundleId: 'com.example.otomobil.RunnerTests',
  );
}
